const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let tab='all',hanja=[],words=[],dictionary={};
async function json(url,options){const response=await fetch(url,{credentials:'same-origin',...options,headers:{'Content-Type':'application/json',...(options?.headers||{})}});if(response.status===401){location.href='/';throw Error('로그인이 필요합니다')}const data=await response.json().catch(()=>({}));if(!response.ok)throw Error(data.detail||'요청에 실패했습니다');return data}
const kataToHira=value=>String(value||'').replace(/[ァ-ヶ]/g,char=>String.fromCharCode(char.charCodeAt(0)-96));
function hanjaCard(item){const read=dictionary[item.character]||{},gloss=[read.meaning,read.sound].filter(Boolean).join(' ')||'뜻·음 정보 없음';return `<article class="word hanja"><div class="glyph" lang="zh-Hant">${esc(item.character)}</div><div><h2>${esc(gloss)}</h2><p><b>훈독</b> ${esc((read.kun||[]).join('・')||'없음')}</p><p><b>음독</b> ${esc((read.on||[]).map(kataToHira).join('・')||'없음')}</p></div><button class="delete" data-hanja="${esc(item.character)}" aria-label="삭제">★</button></article>`}
function wordCard(item){return `<article class="word english"><div class="glyph">EN</div><div><h2>${esc(item.term)}</h2>${item.meaning?`<p><b>뜻</b> ${esc(item.meaning)}</p>`:''}${item.pronunciation?`<p><b>발음</b> ${esc(item.pronunciation)}</p>`:''}${item.note?`<p>${esc(item.note)}</p>`:''}</div><button class="delete" data-id="${item.id}" aria-label="삭제">×</button></article>`}
function render(){const q=$('#search').value.trim().toLowerCase();let html=[];if(tab!=='english')html.push(...hanja.filter(x=>{const d=dictionary[x.character]||{};return !q||`${x.character} ${d.meaning||''} ${d.sound||''}`.toLowerCase().includes(q)}).map(hanjaCard));if(tab!=='hanja')html.push(...words.filter(x=>!q||`${x.term} ${x.meaning} ${x.pronunciation} ${x.note}`.toLowerCase().includes(q)).map(wordCard));$('#list').innerHTML=html.join('')||'<p class="empty">조건에 맞는 단어가 없습니다.</p>';$('#total').textContent=`${hanja.length+words.length}개`}
async function load(){[hanja,words,dictionary]=await Promise.all([json('/api/me/japanese-kanji-favorites'),json('/api/me/vocabulary'),fetch('/static/data/kanjidic-readings.json?v=20260914-hanja-v3').then(r=>r.json())]);render()}
document.querySelectorAll('[data-tab]').forEach(button=>button.onclick=()=>{tab=button.dataset.tab;document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===button));$('#english-form').classList.toggle('hidden',tab!=='english');render()});$('#add-english').onclick=()=>{$('#english-form').classList.remove('hidden');$('#term').focus()};$('#search').oninput=render;
$('#english-form form').onsubmit=async event=>{event.preventDefault();await json('/api/me/vocabulary',{method:'POST',body:JSON.stringify({language:'english',term:$('#term').value,meaning:$('#meaning').value,pronunciation:$('#pronunciation').value,note:$('#note').value})});event.target.reset();words=await json('/api/me/vocabulary');tab='english';document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x.dataset.tab==='english'));render()};
$('#list').onclick=async event=>{const button=event.target.closest('.delete');if(!button)return;if(button.dataset.id){await json(`/api/me/vocabulary/${button.dataset.id}`,{method:'DELETE'});words=words.filter(x=>String(x.id)!==button.dataset.id)}else if(button.dataset.hanja){await json(`/api/me/japanese-kanji-favorites/${encodeURIComponent(button.dataset.hanja)}`,{method:'DELETE'});hanja=hanja.filter(x=>x.character!==button.dataset.hanja)}render()};load().catch(error=>$('#list').innerHTML=`<p class="empty">${esc(error.message)}</p>`);
