const $=s=>document.querySelector(s),esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
let tab="all",hanja=[],words=[],dictionary={},practiceItem=null,drawing=false,recognition=null,speechTranscript="",speechStopTimer=null;
async function json(url,options){const response=await fetch(url,{credentials:"same-origin",...options,headers:{"Content-Type":"application/json",...(options?.headers||{})}});if(response.status===401){location.href="/";throw Error("로그인이 필요합니다")}const data=await response.json().catch(()=>({}));if(!response.ok)throw Error(data.detail||"요청에 실패했습니다");return data}
const kataToHira=value=>String(value||"").replace(/[ァ-ヶ]/g,char=>String.fromCharCode(char.charCodeAt(0)-96));
function actions(kind,key){return `<div class="word-actions"><button data-action="listen" data-kind="${kind}" data-key="${esc(key)}">🔊 듣기</button><button data-action="write" data-kind="${kind}" data-key="${esc(key)}">쓰기</button><button data-action="speak" data-kind="${kind}" data-key="${esc(key)}">말하기</button></div>`}
function hanjaCard(item){const read=dictionary[item.character]||{},gloss=[read.meaning,read.sound].filter(Boolean).join(" ")||"뜻·음 정보 없음";return `<article class="word hanja"><div class="glyph" lang="zh-Hant">${esc(item.character)}</div><div><h2>${esc(gloss)}</h2><p><b>훈독</b> ${esc((read.kun||[]).join("・")||"없음")}</p><p><b>음독</b> ${esc((read.on||[]).map(kataToHira).join("・")||"없음")}</p>${actions("hanja",item.character)}</div><button class="delete" data-hanja="${esc(item.character)}" aria-label="삭제">★</button></article>`}
function wordCard(item){const english=item.language==="english";return `<article class="word english"><div class="glyph">${english?"EN":"日"}</div><div><h2>${esc(item.term)}</h2>${item.meaning?`<p><b>뜻</b> ${esc(item.meaning)}</p>`:""}${item.pronunciation?`<p><b>발음</b> ${esc(item.pronunciation)}</p>`:""}${item.note?`<p>${esc(item.note)}</p>`:""}${actions("word",item.id)}</div><button class="delete" data-id="${item.id}" aria-label="삭제">×</button></article>`}
function render(){const q=$("#search").value.trim().toLowerCase(),html=[];if(tab!=="english")html.push(...hanja.filter(x=>{const d=dictionary[x.character]||{};return !q||`${x.character} ${d.meaning||""} ${d.sound||""}`.toLowerCase().includes(q)}).map(hanjaCard));if(tab!=="hanja")html.push(...words.filter(x=>!q||`${x.term} ${x.meaning} ${x.pronunciation} ${x.note}`.toLowerCase().includes(q)).map(wordCard));$("#list").innerHTML=html.join("")||'<p class="empty">조건에 맞는 단어가 없습니다.</p>';$("#total").textContent=`${hanja.length+words.length}개`}
async function load(){const [savedHanja,savedWords,dictionaryFile]=await Promise.all([json("/api/me/japanese-kanji-favorites"),json("/api/me/vocabulary"),fetch("/static/data/kanjidic-readings.json?v=20260915-hanja-v4",{cache:"no-cache"}).then(r=>{if(!r.ok)throw Error(`한자 사전 HTTP ${r.status}`);return r.json()})]);hanja=savedHanja;words=savedWords;dictionary=dictionaryFile.entries||dictionaryFile;render()}
function itemFor(kind,key){if(kind==="hanja"){const d=dictionary[key]||{},kun=(d.kun||[]).map(kataToHira).filter(Boolean),on=(d.on||[]).map(kataToHira).filter(Boolean),pronunciation=kun[0]||on[0]||key,parts=[];if(kun.length)parts.push(`訓読み、${kun.join("、")}`);if(on.length)parts.push(`音読み、${on.join("、")}`);return{term:key,speakText:parts.length?parts.join("。"):`漢字、${key}`,pronunciation,language:"japanese"}}const item=words.find(word=>String(word.id)===String(key));return item?{term:item.term,speakText:item.term,pronunciation:item.pronunciation||item.term,language:item.language==="english"?"english":"japanese"}:null}
function speak(item=practiceItem){if(!item||!("speechSynthesis" in window))return;speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(item.speakText||item.term);utterance.lang=item.language==="english"?"en-US":"ja-JP";utterance.rate=.88;utterance.voice=speechSynthesis.getVoices().find(v=>v.lang.toLowerCase().startsWith(item.language==="english"?"en":"ja"))||null;speechSynthesis.speak(utterance)}
function openPractice(mode,item){practiceItem=item;$("#practice").classList.remove("hidden");document.body.classList.add("practice-open");$("#practice-score").classList.add("hidden");$("#practice-target").textContent=item.term;$("#write-pane").classList.toggle("hidden",mode!=="write");$("#speak-pane").classList.toggle("hidden",mode!=="speak");$("#practice-title").textContent=mode==="write"?"단어 따라 쓰기":"발음 점수";$("#practice-guide").textContent=mode==="write"?"단어를 보고 발음을 들은 뒤 아래 칸에 손으로 써보세요.":"단어를 들은 뒤 녹음 시작을 누르고 그대로 말해보세요.";if(mode==="write"){clearCanvas();speak()}else{$("#speech-result").textContent="먼저 단어를 듣고 녹음을 시작하세요.";$("#speech-meter-bar").style.width="0%";speak()}}
function closePractice(){clearTimeout(speechStopTimer);speechStopTimer=null;recognition?.abort?.();recognition=null;speechSynthesis?.cancel();$("#practice").classList.add("hidden");document.body.classList.remove("practice-open");$("#speech-record").textContent="● 녹음 시작";$("#speech-record").classList.remove("recording")}
function context(){const c=$("#write-canvas").getContext("2d",{willReadFrequently:true});c.lineCap="round";c.lineJoin="round";c.strokeStyle=getComputedStyle(document.documentElement).getPropertyValue("--ink")||"#fff";c.lineWidth=18;return c}
function clearCanvas(){const c=$("#write-canvas");context().clearRect(0,0,c.width,c.height)}
function normalizedInk(imageData,size=72){const{data,width,height}=imageData;let minX=width,minY=height,maxX=-1,maxY=-1;for(let y=0;y<height;y+=2)for(let x=0;x<width;x+=2)if(data[(y*width+x)*4+3]>20){minX=Math.min(minX,x);minY=Math.min(minY,y);maxX=Math.max(maxX,x);maxY=Math.max(maxY,y)}if(maxX<0)return null;const src=document.createElement("canvas");src.width=width;src.height=height;src.getContext("2d").putImageData(imageData,0,0);const out=document.createElement("canvas");out.width=size;out.height=size;const ctx=out.getContext("2d"),bw=maxX-minX+1,bh=maxY-minY+1,scale=Math.min((size-8)/bw,(size-8)/bh),dw=bw*scale,dh=bh*scale;ctx.drawImage(src,minX,minY,bw,bh,(size-dw)/2,(size-dh)/2,dw,dh);const pixels=ctx.getImageData(0,0,size,size).data;return Uint8Array.from({length:size*size},(_,i)=>pixels[i*4+3]>25?1:0)}
function targetInk(text){const c=document.createElement("canvas");c.width=640;c.height=440;const ctx=c.getContext("2d");ctx.fillStyle="#fff";ctx.textAlign="center";ctx.textBaseline="middle";ctx.font=`${Math.max(58,Math.min(180,520/[...text].length))}px "Hiragino Sans","Yu Gothic",sans-serif`;ctx.fillText(text,320,230,590);return normalizedInk(ctx.getImageData(0,0,640,440))}
function dilate(mask,size=72){const out=new Uint8Array(mask.length);for(let y=0;y<size;y++)for(let x=0;x<size;x++)if(mask[y*size+x])for(let dy=-3;dy<=3;dy++)for(let dx=-3;dx<=3;dx++){const nx=x+dx,ny=y+dy;if(nx>=0&&nx<size&&ny>=0&&ny<size)out[ny*size+nx]=1}return out}
function writingScore(){const c=$("#write-canvas"),user=normalizedInk(context().getImageData(0,0,c.width,c.height)),target=targetInk(practiceItem.term);if(!user||!target)return 0;const wu=dilate(user),wt=dilate(target);let uc=0,tc=0,uh=0,th=0;for(let i=0;i<user.length;i++){if(user[i]){uc++;if(wt[i])uh++}if(target[i]){tc++;if(wu[i])th++}}const p=uh/Math.max(1,uc),r=th/Math.max(1,tc);return 100*(2*p*r/Math.max(.001,p+r))}
function showScore(score,message){const rounded=Math.max(0,Math.min(100,Math.round(score))),box=$("#practice-score");box.textContent=`${rounded}점 · ${message}`;box.className=`practice-score score-${rounded>=85?"great":rounded>=65?"good":"retry"}`}
function normalizeSpeech(text,language){let value=String(text||"").normalize("NFKC").toLowerCase();if(language!=="english")value=[...value].map(char=>{const code=char.charCodeAt(0);return code>=0x30a1&&code<=0x30f6?String.fromCharCode(code-0x60):char}).join("");return value.replace(language==="english"?/[^a-z0-9]/g:/[^\u3040-\u309f\u3400-\u9fff]/gu,"")}
function distance(a,b){const prev=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){let left=i,diag=prev[0];prev[0]=i;for(let j=1;j<=b.length;j++){const up=prev[j],value=Math.min(up+1,left+1,diag+(a[i-1]===b[j-1]?0:1));diag=up;prev[j]=value;left=value}}return prev[b.length]}
function startSpeech(){const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition){$("#speech-result").textContent="이 브라우저는 음성 인식을 지원하지 않습니다.";return}if(recognition){const active=recognition;recognition=null;$("#speech-record").textContent="● 다시 녹음";$("#speech-record").classList.remove("recording");try{active.stop()}catch(_error){}if(speechTranscript){const target=normalizeSpeech(practiceItem.term,practiceItem.language),spoken=normalizeSpeech(speechTranscript,practiceItem.language),score=100*(1-distance(target,spoken)/Math.max(1,target.length,spoken.length));showScore(score,score>=85?"원문과 거의 같아요":"빠진 소리를 확인하고 다시 말해보세요")}speechStopTimer=setTimeout(()=>{try{active.abort()}catch(_error){}speechStopTimer=null},700);return}speechTranscript="";const active=new Recognition();recognition=active;active.lang=practiceItem.language==="english"?"en-US":"ja-JP";active.interimResults=true;$("#speech-record").textContent="■ 녹음 중지";$("#speech-record").classList.add("recording");$("#speech-result").textContent="듣고 있어요…";active.onresult=event=>{speechTranscript=[...event.results].map(result=>result[0]?.transcript||"").join("");$("#speech-result").textContent=speechTranscript||"듣고 있어요…";const target=normalizeSpeech(practiceItem.term,practiceItem.language),spoken=normalizeSpeech(speechTranscript,practiceItem.language),score=100*(1-distance(target,spoken)/Math.max(1,target.length,spoken.length));$("#speech-meter-bar").style.width=`${Math.max(0,score)}%`;if(event.results[event.results.length-1].isFinal)showScore(score,score>=85?"원문과 거의 같아요":"빠진 소리를 확인하고 다시 말해보세요")};const finish=()=>{if(recognition===active)recognition=null;$("#speech-record").textContent="● 다시 녹음";$("#speech-record").classList.remove("recording")};active.onend=finish;active.onerror=event=>{finish();$("#speech-result").textContent=event.error==="not-allowed"?"마이크 권한을 허용해 주세요.":"음성을 인식하지 못했어요."};active.start()}
document.querySelectorAll("[data-tab]").forEach(button=>button.onclick=()=>{tab=button.dataset.tab;document.querySelectorAll("[data-tab]").forEach(item=>item.classList.toggle("active",item===button));$("#english-form").classList.toggle("hidden",tab!=="english");render()});$("#add-english").onclick=()=>{$("#english-form").classList.remove("hidden");$("#term").focus()};$("#search").oninput=render;
$("#english-form form").onsubmit=async event=>{event.preventDefault();await json("/api/me/vocabulary",{method:"POST",body:JSON.stringify({language:"english",term:$("#term").value,meaning:$("#meaning").value,pronunciation:$("#pronunciation").value,note:$("#note").value})});event.target.reset();words=await json("/api/me/vocabulary");tab="english";render()};
$("#list").onclick=async event=>{const action=event.target.closest("[data-action]");if(action){const item=itemFor(action.dataset.kind,action.dataset.key);if(!item)return;if(action.dataset.action==="listen")speak(item);else openPractice(action.dataset.action,item);return}const button=event.target.closest(".delete");if(!button)return;if(button.dataset.id){await json(`/api/me/vocabulary/${button.dataset.id}`,{method:"DELETE"});words=words.filter(x=>String(x.id)!==button.dataset.id)}else if(button.dataset.hanja){await json(`/api/me/japanese-kanji-favorites/${encodeURIComponent(button.dataset.hanja)}`,{method:"DELETE"});hanja=hanja.filter(x=>x.character!==button.dataset.hanja)}render()};
$("#practice-close").onclick=closePractice;$("#practice").onclick=event=>{if(event.target===$("#practice"))closePractice()};$("#practice-listen").onclick=()=>speak();$("#speech-record").onclick=startSpeech;$("#write-clear").onclick=clearCanvas;$("#write-grade").onclick=()=>{const score=writingScore();showScore(score,score>=85?"단어를 아주 정확하게 썼어요":score>=65?"좋아요. 획 위치를 조금만 다듬어보세요":"단어를 보면서 천천히 다시 써보세요")};
const canvas=$("#write-canvas");function point(event){const rect=canvas.getBoundingClientRect(),p=event;return{x:(p.clientX-rect.left)*canvas.width/rect.width,y:(p.clientY-rect.top)*canvas.height/rect.height}}canvas.addEventListener("pointerdown",event=>{event.preventDefault();drawing=true;const p=point(event),ctx=context();ctx.beginPath();ctx.moveTo(p.x,p.y);canvas.setPointerCapture?.(event.pointerId)});canvas.addEventListener("pointermove",event=>{if(!drawing)return;event.preventDefault();const p=point(event),ctx=context();ctx.lineTo(p.x,p.y);ctx.stroke()});window.addEventListener("pointerup",()=>drawing=false);load().catch(error=>$("#list").innerHTML=`<p class="empty">${esc(error.message)}</p>`);
