const $=id=>document.getElementById(id);
let sourceFile=null,objectUrl=null,duration=0,peaks=[],cuts=[],selection=null,dragStart=null,drawing=false;
const audio=$("audio"),canvas=$("waveform"),ctx=canvas.getContext("2d");
function formatTime(value){const safe=Math.max(0,Number(value)||0),minutes=Math.floor(safe/60),seconds=safe-minutes*60;return`${String(minutes).padStart(2,"0")}:${seconds.toFixed(1).padStart(4,"0")}`}
function status(text,error=false){const el=$("status");el.textContent=text;el.style.background=error?"#8e3342":"#2d2930";el.classList.remove("hidden");clearTimeout(status.timer);status.timer=setTimeout(()=>el.classList.add("hidden"),5000)}
function mergeCuts(items){const sorted=items.map(x=>({start:Math.max(0,Math.min(duration,x.start)),end:Math.max(0,Math.min(duration,x.end))})).filter(x=>x.end-x.start>=.05).sort((a,b)=>a.start-b.start),merged=[];for(const item of sorted){const last=merged.at(-1);if(last&&item.start<=last.end+.001)last.end=Math.max(last.end,item.end);else merged.push(item)}return merged}
function cutAt(time){return cuts.find(cut=>time>=cut.start-.01&&time<cut.end-.01)}
function resizeCanvas(){const rect=canvas.getBoundingClientRect(),ratio=window.devicePixelRatio||1,width=Math.max(1,Math.round(rect.width*ratio)),height=Math.max(1,Math.round(rect.height*ratio));if(canvas.width!==width||canvas.height!==height){canvas.width=width;canvas.height=height}draw()}
function draw(){if(!duration)return;const w=canvas.width,h=canvas.height,ratio=window.devicePixelRatio||1,style=getComputedStyle(document.documentElement);ctx.clearRect(0,0,w,h);ctx.fillStyle=getComputedStyle(document.body).backgroundColor;ctx.fillRect(0,0,w,h);ctx.strokeStyle=style.getPropertyValue("--line");ctx.lineWidth=ratio;const marks=Math.max(4,Math.floor(w/(90*ratio)));ctx.font=`${10*ratio}px sans-serif`;ctx.fillStyle=style.getPropertyValue("--muted");for(let i=0;i<=marks;i++){const x=i/marks*w;ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke();ctx.fillText(formatTime(i/marks*duration).slice(0,-2),x+4*ratio,18*ratio)}const mid=h*.55;ctx.strokeStyle=style.getPropertyValue("--wave");ctx.lineWidth=Math.max(1,ratio);ctx.beginPath();for(let i=0;i<peaks.length;i++){const x=i/(peaks.length-1)*w,amp=peaks[i]*h*.37;ctx.moveTo(x,mid-amp);ctx.lineTo(x,mid+amp)}ctx.stroke();for(const cut of cuts){ctx.fillStyle=style.getPropertyValue("--cut");ctx.fillRect(cut.start/duration*w,0,(cut.end-cut.start)/duration*w,h)}if(selection){ctx.fillStyle="rgba(240,95,120,.2)";ctx.fillRect(selection.start/duration*w,0,(selection.end-selection.start)/duration*w,h);ctx.strokeStyle="#f05f78";ctx.lineWidth=2*ratio;for(const point of [selection.start,selection.end]){const x=point/duration*w;ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}}const head=audio.currentTime/duration*w;ctx.strokeStyle="#f02f55";ctx.lineWidth=2*ratio;ctx.beginPath();ctx.moveTo(head,0);ctx.lineTo(head,h);ctx.stroke();if(!audio.paused)requestAnimationFrame(draw)}
async function buildWaveform(file){const context=new(window.AudioContext||window.webkitAudioContext)();try{const buffer=await context.decodeAudioData(await file.arrayBuffer()),channel=buffer.getChannelData(0),bins=Math.min(1600,Math.max(500,Math.floor(canvas.clientWidth*2))),step=Math.max(1,Math.floor(channel.length/bins));peaks=[];for(let i=0;i<bins;i++){let max=0;const start=i*step,end=Math.min(channel.length,start+step);for(let j=start;j<end;j++)max=Math.max(max,Math.abs(channel[j]));peaks.push(max)}duration=buffer.duration}finally{await context.close()}resizeCanvas()}
function renderCuts(){const list=$("cut-list");list.replaceChildren();if(!cuts.length){const p=document.createElement("p");p.textContent="아직 잘라낼 구간이 없습니다.";list.append(p)}cuts.forEach((cut,index)=>{const row=document.createElement("div"),text=document.createElement("span"),remove=document.createElement("button");row.className="cut-item";text.textContent=`${formatTime(cut.start)} – ${formatTime(cut.end)} · ${(cut.end-cut.start).toFixed(1)}초`;remove.textContent="취소";remove.addEventListener("click",()=>{cuts.splice(index,1);renderCuts();draw()});row.append(text,remove);list.append(row)});$("undo").disabled=!cuts.length;$("export").disabled=!sourceFile;draw()}
function renderSelection(){if(selection&&selection.end-selection.start>=.05){$("selection-time").textContent=`${formatTime(selection.start)} – ${formatTime(selection.end)} · ${(selection.end-selection.start).toFixed(1)}초`;$("delete-selection").disabled=false}else{$("selection-time").textContent="구간을 파형에서 드래그하세요";$("delete-selection").disabled=true}draw()}
async function loadFile(file){if(!file)return;if(!/\.mp3$/i.test(file.name)){status("MP3 파일을 선택해주세요.",true);return}sourceFile=file;cuts=[];selection=null;peaks=[];duration=0;if(objectUrl)URL.revokeObjectURL(objectUrl);objectUrl=URL.createObjectURL(file);audio.src=objectUrl;$("filename").textContent=file.name;$("filemeta").textContent=`${(file.size/1024/1024).toFixed(1)}MB`;$("editor").classList.remove("hidden");$("loading").classList.remove("hidden");$("file").closest("label").classList.add("hidden");try{await new Promise((resolve,reject)=>{audio.onloadedmetadata=resolve;audio.onerror=reject});await buildWaveform(file);$("duration").textContent=formatTime(duration);$("filemeta").textContent+=` · ${formatTime(duration)}`;renderCuts();renderSelection()}catch(e){status("이 MP3의 파형을 분석하지 못했습니다.",true)}finally{$("loading").classList.add("hidden")}}
function seek(value){audio.currentTime=Math.max(0,Math.min(duration,value));$("current").textContent=formatTime(audio.currentTime);draw()}
function timeFromEvent(event){const rect=canvas.getBoundingClientRect();return Math.max(0,Math.min(duration,(event.clientX-rect.left)/rect.width*duration))}
canvas.addEventListener("pointerdown",event=>{dragStart=timeFromEvent(event);canvas.setPointerCapture(event.pointerId)});
canvas.addEventListener("pointermove",event=>{if(dragStart===null)return;const now=timeFromEvent(event);selection={start:Math.min(dragStart,now),end:Math.max(dragStart,now)};renderSelection()});
canvas.addEventListener("pointerup",event=>{const end=timeFromEvent(event);if(Math.abs(end-dragStart)<duration*.003){selection=null;seek(end)}else selection={start:Math.min(dragStart,end),end:Math.max(dragStart,end)};dragStart=null;renderSelection()});
$("file").addEventListener("change",event=>loadFile(event.target.files[0]));$("replace").addEventListener("click",()=>$("file").click());
$("play").addEventListener("click",async()=>{if(audio.paused){const cut=cutAt(audio.currentTime);if(cut)seek(cut.end);await audio.play();$("play").textContent="Ⅱ";draw()}else{audio.pause();$("play").textContent="▶"}});
$("back").addEventListener("click",()=>seek(audio.currentTime-5));$("forward").addEventListener("click",()=>seek(audio.currentTime+5));
audio.addEventListener("timeupdate",()=>{const cut=cutAt(audio.currentTime);if(cut)audio.currentTime=cut.end;$("current").textContent=formatTime(audio.currentTime)});audio.addEventListener("ended",()=>{$("play").textContent="▶";draw()});audio.addEventListener("pause",()=>{$("play").textContent="▶";draw()});
$("mark-start").addEventListener("click",()=>{selection={start:audio.currentTime,end:selection?.end??Math.min(duration,audio.currentTime+1)};if(selection.end<selection.start)[selection.start,selection.end]=[selection.end,selection.start];renderSelection()});
$("mark-end").addEventListener("click",()=>{selection={start:selection?.start??Math.max(0,audio.currentTime-1),end:audio.currentTime};if(selection.end<selection.start)[selection.start,selection.end]=[selection.end,selection.start];renderSelection()});
$("delete-selection").addEventListener("click",()=>{if(!selection)return;cuts=mergeCuts([...cuts,selection]);selection=null;renderCuts();renderSelection()});$("undo").addEventListener("click",()=>{cuts.pop();renderCuts()});
$("export").addEventListener("click",async()=>{if(!sourceFile)return;const button=$("export"),form=new FormData();form.append("file",sourceFile,sourceFile.name);form.append("cuts",JSON.stringify(cuts));button.disabled=true;button.textContent="처리 중";status("삭제 구간을 잘라내고 MP3를 만드는 중입니다…");try{const response=await fetch("/api/audio-editor/export",{method:"POST",credentials:"same-origin",body:form});if(!response.ok){const data=await response.json().catch(()=>({}));throw new Error(data.detail||"내보내지 못했습니다")};const blob=await response.blob(),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`${sourceFile.name.replace(/\.mp3$/i,"")}-편집본.mp3`;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);status("편집한 MP3 다운로드를 시작했습니다.")}catch(e){status(e.message,true)}finally{button.disabled=false;button.textContent="내보내기"}});
window.addEventListener("resize",resizeCanvas);window.matchMedia("(prefers-color-scheme: dark)").addEventListener?.("change",draw);
