const $ = id => document.getElementById(id);
let currentStatus = null;
let timeProfileInitialized = false;
function notice(message, error=false){const el=$("notice");el.textContent=message;el.classList.remove("hidden","error");if(error)el.classList.add("error");else setTimeout(()=>el.classList.add("hidden"),3500)}
async function api(url,options={}){const response=await fetch(url,{credentials:"same-origin",...options,headers:{"Content-Type":"application/json",...(options.headers||{})}});if(response.status===401){location.href="/";throw new Error("로그인이 필요합니다")}const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.detail||"요청을 처리하지 못했습니다");return data}
function metric(label,value,detail=""){const el=document.createElement("article"),small=document.createElement("small"),strong=document.createElement("strong"),span=document.createElement("span");el.className="metric";small.textContent=label;strong.className="value";strong.textContent=value??"—";span.className="detail";span.textContent=detail;el.append(small,strong,span);return el}
function checkRow(label,checked,time,onToggle=null,onDelete=null){const row=document.createElement("div"),dot=document.createElement(onToggle?"button":"span"),text=document.createElement("span");row.className=`check-row${checked?" done":""}`;dot.className="check-dot";dot.textContent=checked?"✓":"";if(onToggle){dot.type="button";dot.setAttribute("aria-label",`${label} ${checked?"체크 해제":"체크"}`);dot.addEventListener("click",()=>onToggle(!checked,row))}text.textContent=label;row.append(dot,text);if(time){const clock=document.createElement("time");clock.textContent=time;row.append(clock)}if(onDelete){const del=document.createElement("button");del.type="button";del.className="check-delete";del.textContent="삭제";del.setAttribute("aria-label",`${label} 삭제`);del.addEventListener("click",()=>onDelete(row));row.append(del);let startX=null;row.addEventListener("touchstart",e=>{startX=e.touches[0].clientX},{passive:true});row.addEventListener("touchmove",e=>{if(startX!==null&&e.touches[0].clientX-startX<-35)row.classList.add("swiping")},{passive:true});row.addEventListener("touchend",e=>{const delta=startX===null?0:e.changedTouches[0].clientX-startX;startX=null;row.classList.remove("swiping");if(delta<-80)onDelete(row)},{passive:true})}return row}
function empty(text){const el=document.createElement("div");el.className="empty";el.textContent=text;return el}
function render(data){currentStatus=data;$("summary").replaceChildren(
  metric("오늘 근무",data.shift||"미정",data.shift_day_number?`${data.shift_day_number}일차${data.shift_is_last_day?" · 마지막 날":""}`:""),
  metric("오늘 날씨",data.weather||"확인 중",data.storage_free_gb==null?"저장공간 확인 중":`저장공간 ${data.storage_free_gb}GB`),
  metric("Codex",data.codex_percent==null?"—":`${data.codex_percent}%`,data.codex_window_day?`${data.codex_window_day}/${data.codex_window_days}일차`:"사용량"),
  metric("Claude",data.claude_percent==null?"—":`${data.claude_percent}%`,data.earnings_short||"사용량"));
 const today=$("today-reminders");today.replaceChildren();const details=data.reminders_detailed||(data.reminders||[]).map(label=>({label,checked:Boolean((data.reminders_checked||{})[label]),time:null}));if(!details.length)today.append(empty("오늘 예정된 리마인더가 없습니다."));details.forEach(item=>{let busy=false;const toggle=async(next,row)=>{if(busy)return;busy=true;row.querySelectorAll("button").forEach(button=>button.disabled=true);try{await api("/api/shift-alarm/reminder-check",{method:"PUT",body:JSON.stringify({label:item.label,checked:next})});item.checked=next;render(data)}catch(e){notice(e.message,true);row.querySelectorAll("button").forEach(button=>button.disabled=false);busy=false}};const remove=async row=>{if(busy||!confirm("이 리마인더를 오늘 목록에서 삭제할까요? 반복 설정은 유지됩니다."))return;busy=true;row.querySelectorAll("button").forEach(button=>button.disabled=true);try{await api(`/api/shift-alarm/reminder?label=${encodeURIComponent(item.label)}`,{method:"DELETE"});data.reminders_detailed=details.filter(entry=>entry!==item);render(data);notice("오늘의 리마인더에서 삭제했습니다.")}catch(e){notice(e.message,true);row.classList.remove("swiping");row.querySelectorAll("button").forEach(button=>button.disabled=false);busy=false}};today.append(checkRow(item.label,item.checked,item.time,toggle,remove))});
 const routine=$("routine");routine.replaceChildren();const routines=data.daily_routine||[];if(!routines.length)routine.append(empty("Shift Alarm에서 일일 루틴을 불러오는 중입니다."));routines.forEach(item=>routine.append(checkRow(item.label,item.checked)));$("routine-count").textContent=`(${routines.filter(item=>item.checked).length}/${routines.length})`;$("check-all").disabled=!routines.some(item=>!item.checked);
 const profileSelect=$("time-profile");if(!timeProfileInitialized){const preferred=data.reminder_time_profile||data.shift||"시각";if([...profileSelect.options].some(option=>option.value===preferred))profileSelect.value=preferred;timeProfileInitialized=true}const profile=profileSelect.value;const schedule=$("schedule");schedule.replaceChildren();(data.reminder_schedule||[]).forEach(item=>{const row=document.createElement("tr"),label=document.createElement("td"),timeCell=document.createElement("td"),input=document.createElement("input"),enabled=document.createElement("td"),action=document.createElement("td"),save=document.createElement("button");label.textContent=item.label;input.type="time";input.value=(item.times||{})[profile]||item.time||"";input.setAttribute("aria-label",`${item.label} ${profile} 시각`);input.disabled=item.editable===false;timeCell.append(input);enabled.textContent=item.editable===false?"자동":item.enabled?"켜짐":"꺼짐";enabled.className=item.enabled?"status-on":"status-off";save.type="button";save.textContent="저장";if(item.editable===false){save.disabled=true;save.title="근무표와 전환 날짜에 따라 자동 계산됩니다"}else{save.addEventListener("click",async()=>{save.disabled=true;try{await api("/api/shift-alarm/reminder-time",{method:"PUT",body:JSON.stringify({label:item.label,time:input.value,profile})});item.times=item.times||{};item.times[profile]=input.value;if(profile==="시각")item.time=input.value;notice(`${profile} 시각을 저장했습니다. Shift Alarm이 곧 동기화합니다.`)}catch(e){notice(e.message,true)}finally{save.disabled=false}})}action.append(save);row.append(label,timeCell,enabled,action);schedule.append(row)});if(!(data.reminder_schedule||[]).length){const row=document.createElement("tr"),cell=document.createElement("td");cell.colSpan=4;cell.className="empty";cell.textContent="Shift Alarm을 재시작하면 전체 시각표가 표시됩니다.";row.append(cell);schedule.append(row)}
 const notion=$("notion-link");if(data.reminder_notion_url)notion.href=data.reminder_notion_url;else notion.classList.add("hidden");$("updated").textContent=data.updated_at?`Shift Alarm 최종 갱신 ${new Date(data.updated_at).toLocaleString("ko-KR")}`:""}
async function load(){$("refresh").disabled=true;try{render(await api("/api/shift-alarm/status"))}catch(e){notice(e.message,true)}finally{$("refresh").disabled=false}}
$("refresh").addEventListener("click",load);$("time-profile").addEventListener("change",()=>currentStatus&&render(currentStatus));$("check-all").addEventListener("click",async()=>{if(!currentStatus?.daily_routine?.length||!confirm("남아 있는 오늘의 일일 루틴을 모두 체크할까요?"))return;$("check-all").disabled=true;try{const result=await api("/api/shift-alarm/routine/check-all",{method:"POST"});currentStatus.daily_routine.forEach(item=>item.checked=true);render(currentStatus);notice(`${result.updated}개 루틴을 체크했습니다.`)}catch(e){notice(e.message,true);$("check-all").disabled=false}});load();
