const $=s=>document.querySelector(s),W=2400,H=1800,O={x:1200,y:900};let memos=[],current=null,dialogMode=null,view={x:0,y:0,scale:1},pan=null,pinch=null;const pointers=new Map();
async function api(path,options={}){const r=await fetch(path,{credentials:"same-origin",headers:{"Content-Type":"application/json",...(options.headers||{})},...options}),data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.detail||"요청을 처리하지 못했습니다");return data}
function esc(v=""){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function toast(v){const e=$("#toast");e.textContent=v;e.classList.remove("hidden");setTimeout(()=>e.classList.add("hidden"),1800)}
async function load(id){memos=await api("/api/me/memos");renderList();const wanted=id||Number(new URLSearchParams(location.search).get("memo"));if(wanted)selectMemo(wanted);else if(current)selectMemo(current.id);else if(memos[0])selectMemo(memos[0].id)}
function renderList(){const q=$("#search").value.trim().toLowerCase(),list=memos.filter(m=>`${m.title} ${m.note} ${m.source_content}`.toLowerCase().includes(q));$("#memo-list").innerHTML=list.length?list.map(m=>`<button data-id="${m.id}" class="${current?.id===m.id?'active':''}"><strong>${esc(m.title)}</strong><span>${esc(m.note||m.source_content||"빈 메모")}</span></button>`).join(""):"<p>저장된 메모가 없습니다.</p>";$("#memo-list").querySelectorAll("button").forEach(b=>b.onclick=()=>selectMemo(+b.dataset.id))}
function selectMemo(id){current=memos.find(m=>m.id===id);if(!current)return;history.replaceState(null,"",`?memo=${id}`);$("#empty").classList.add("hidden");$("#editor").classList.remove("hidden");$("#memo-title").value=current.title;$("#memo-note").value=current.note;const source=!!current.source_message_id;$("#source-card").classList.toggle("hidden",!source);$("#source-label").textContent=source?`채팅방 ${current.source_room_id||""}`:"직접 작성한 메모";$("#source-sender").textContent=current.source_sender;$("#source-content").textContent=current.source_content;renderMap();renderList();requestAnimationFrame(fitMap)}
function layout(){const children=new Map(),positions=new Map([[0,{...O}]]);current.nodes.forEach(n=>{const k=n.parent_id??0;if(!children.has(k))children.set(k,[]);children.get(k).push(n)});const roots=children.get(0)||[];roots.forEach((n,i)=>place(n,-Math.PI/2+Math.PI*2*i/Math.max(1,roots.length),1));function place(n,a,d){const p=positions.get(n.parent_id??0)||O,dist=d===1?310:Math.max(205,265-d*12);positions.set(n.id,{x:p.x+Math.cos(a)*dist,y:p.y+Math.sin(a)*dist});const list=children.get(n.id)||[],spread=Math.min(1.05,.32+list.length*.14);list.forEach((c,i)=>place(c,a+(list.length===1?0:-spread/2+spread*i/(list.length-1)),d+1))}return positions}
function renderMap(){const pos=layout(),rootText=current.note||current.source_content||"여기서 생각을 확장해보세요";$("#memo-tree").innerHTML=`<article class="node-card root" style="left:${O.x}px;top:${O.y}px"><small>ROOT NOTE</small><h3>${esc(current.title)}</h3><p>${esc(rootText)}</p><div class="node-actions"><button data-add-root>＋ 가지 만들기</button></div></article>`+current.nodes.map(n=>{const p=pos.get(n.id);return `<article class="node-card" style="left:${p.x}px;top:${p.y}px"><p>${esc(n.content)}</p><div class="node-actions"><button data-add="${n.id}">＋ 가지</button><button data-edit="${n.id}">수정</button><button data-delete="${n.id}" class="danger">삭제</button></div></article>`}).join("");$("#mindmap-lines").innerHTML=current.nodes.map(n=>{const a=pos.get(n.parent_id??0)||O,b=pos.get(n.id),dx=b.x-a.x;return `<path d="M ${a.x} ${a.y} C ${a.x+dx*.45} ${a.y}, ${b.x-dx*.35} ${b.y}, ${b.x} ${b.y}"/>`}).join("");$("[data-add-root]").onclick=()=>openNode("add",null);$("#memo-tree").querySelectorAll("[data-add]").forEach(b=>b.onclick=()=>openNode("add",+b.dataset.add));$("#memo-tree").querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>openNode("edit",+b.dataset.edit));$("#memo-tree").querySelectorAll("[data-delete]").forEach(b=>b.onclick=()=>removeNode(+b.dataset.delete))}
function applyView(){$("#mindmap-stage").style.transform=`translate(${view.x}px,${view.y}px) scale(${view.scale})`;$("#zoom-level").textContent=`${Math.round(view.scale*100)}%`}
function zoom(scale,x,y){const r=$("#mindmap-viewport").getBoundingClientRect(),px=(x??r.left+r.width/2)-r.left,py=(y??r.top+r.height/2)-r.top,wx=(px-view.x)/view.scale,wy=(py-view.y)/view.scale;view.scale=Math.min(2.4,Math.max(.28,scale));view.x=px-wx*view.scale;view.y=py-wy*view.scale;applyView()}
function fitMap(){if(!current)return;const v=$("#mindmap-viewport"),cards=[...$("#memo-tree").querySelectorAll(".node-card")],xs=cards.map(c=>parseFloat(c.style.left)),ys=cards.map(c=>parseFloat(c.style.top)),minX=Math.min(...xs)-180,maxX=Math.max(...xs)+180,minY=Math.min(...ys)-130,maxY=Math.max(...ys)+130;view.scale=Math.max(.28,Math.min(1,(v.clientWidth-40)/(maxX-minX),(v.clientHeight-40)/(maxY-minY)));view.x=v.clientWidth/2-(minX+maxX)/2*view.scale;view.y=v.clientHeight/2-(minY+maxY)/2*view.scale;applyView()}
function gestures(){const v=$("#mindmap-viewport");v.addEventListener("wheel",e=>{e.preventDefault();zoom(view.scale*Math.exp(-e.deltaY*.0015),e.clientX,e.clientY)},{passive:false});v.addEventListener("pointerdown",e=>{if(e.target.closest("button,.node-card"))return;v.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===1)pan={x:e.clientX,y:e.clientY,vx:view.x,vy:view.y};if(pointers.size===2){const[a,b]=[...pointers.values()];pinch={d:Math.hypot(a.x-b.x,a.y-b.y),scale:view.scale}}});v.addEventListener("pointermove",e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2&&pinch){const[a,b]=[...pointers.values()];zoom(pinch.scale*Math.hypot(a.x-b.x,a.y-b.y)/Math.max(1,pinch.d),(a.x+b.x)/2,(a.y+b.y)/2)}else if(pan){view.x=pan.vx+e.clientX-pan.x;view.y=pan.vy+e.clientY-pan.y;applyView()}});const end=e=>{pointers.delete(e.pointerId);pan=null;pinch=null};v.addEventListener("pointerup",end);v.addEventListener("pointercancel",end)}
function openNode(mode,id=null){dialogMode={mode,id};$("#node-dialog-title").textContent=mode==="edit"?"파생 메모 수정":"새 파생 메모";$("#node-content").value=mode==="edit"?current.nodes.find(n=>n.id===id)?.content||"":"";$("#node-dialog").showModal();setTimeout(()=>$("#node-content").focus(),50)}
const activeVoiceInputs=new WeakMap();
function resetVoiceButton(button){button.classList.remove("listening");button.textContent="🎙️ 음성";button.setAttribute("aria-label","음성으로 메모 입력")}
function startVoiceInput(target,button){
  const active=activeVoiceInputs.get(button);
  if(active){active.stopping=true;button.disabled=true;active.recognition.stop();return}
  const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition){alert("이 브라우저에서는 음성 입력을 지원하지 않습니다. macOS Safari 또는 Chrome에서 마이크 권한을 허용해주세요.");return}
  const recognition=new Recognition(),state={recognition,stopping:false,finalText:"",interimText:""};recognition.lang="ko-KR";recognition.interimResults=true;recognition.continuous=true;const original=target.value,separator=original.trim()?" ":"";
  activeVoiceInputs.set(button,state);button.classList.add("listening");button.textContent="■ 정지";button.setAttribute("aria-label","음성 메모 녹음 정지");
  recognition.onresult=event=>{let interim="";for(let index=event.resultIndex;index<event.results.length;index++){const text=event.results[index][0].transcript;if(event.results[index].isFinal)state.finalText+=text;else interim+=text}state.interimText=interim;target.value=original+separator+state.finalText+state.interimText;target.dispatchEvent(new Event("input",{bubbles:true}))};
  recognition.onerror=event=>{if(event.error==="aborted"||event.error==="no-speech"||state.stopping)return;const message=event.error==="not-allowed"?"마이크 권한이 꺼져 있습니다. 브라우저의 사이트 설정에서 마이크를 허용해주세요.":`음성 입력 오류: ${event.error}`;toast(message)};
  recognition.onend=()=>{if(activeVoiceInputs.get(button)!==state)return;activeVoiceInputs.delete(button);button.disabled=false;resetVoiceButton(button);target.focus()};
  try{recognition.start()}catch(error){activeVoiceInputs.delete(button);button.disabled=false;resetVoiceButton(button);if(error.name!=="AbortError")toast("음성 입력을 시작하지 못했습니다. 잠시 후 다시 시도해주세요.")}
}
async function removeNode(id){if(!confirm("이 가지와 아래에 연결된 메모를 모두 삭제할까요?"))return;await api(`/api/me/memo-nodes/${id}`,{method:"DELETE"});await load(current.id);toast("가지를 삭제했습니다")}
$("#node-dialog").addEventListener("close",async()=>{if($("#node-dialog").returnValue!=="default"||!dialogMode)return;const content=$("#node-content").value.trim();if(!content)return toast("내용을 입력하세요");try{if(dialogMode.mode==="edit")await api(`/api/me/memo-nodes/${dialogMode.id}`,{method:"PUT",body:JSON.stringify({content})});else await api(`/api/me/memos/${current.id}/nodes`,{method:"POST",body:JSON.stringify({parent_id:dialogMode.id,content})});await load(current.id);toast("메모를 연결했습니다")}catch(e){alert(e.message)}});
$("#node-save").onclick=()=>$("#node-dialog").close("default");$("#add-root-node").onclick=()=>openNode("add",null);$("#search").oninput=renderList;$("#zoom-in").onclick=()=>zoom(view.scale*1.22);$("#zoom-out").onclick=()=>zoom(view.scale/1.22);$("#zoom-fit").onclick=fitMap;
$("#new-memo").onclick=async()=>{try{const r=await api("/api/me/memos",{method:"POST",body:JSON.stringify({title:"새 메모",note:""})});await load(r.id);$("#memo-title").focus()}catch(e){alert(e.message)}};$("#save-root").onclick=async()=>{try{await api(`/api/me/memos/${current.id}`,{method:"PUT",body:JSON.stringify({title:$("#memo-title").value,note:$("#memo-note").value})});await load(current.id);toast("저장했습니다")}catch(e){alert(e.message)}};$("#delete-root").onclick=async()=>{if(!confirm("이 메모와 모든 가지를 삭제할까요?"))return;await api(`/api/me/memos/${current.id}`,{method:"DELETE"});current=null;history.replaceState(null,"","/memo/");$("#editor").classList.add("hidden");$("#empty").classList.remove("hidden");await load()};gestures();load().catch(e=>{$("#empty").innerHTML=`<b>메모를 불러오지 못했습니다</b><p>${esc(e.message)}</p>`});
$("#memo-voice").onclick=event=>startVoiceInput($("#memo-note"),event.currentTarget);$("#node-voice").onclick=event=>startVoiceInput($("#node-content"),event.currentTarget);
