const $=s=>document.querySelector(s);let memos=[],current=null,dialogMode=null;
async function api(path,options={}){const r=await fetch(path,{credentials:"same-origin",headers:{"Content-Type":"application/json",...(options.headers||{})},...options});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.detail||"요청을 처리하지 못했습니다");return data}
function toast(message){const el=$("#toast");el.textContent=message;el.classList.remove("hidden");setTimeout(()=>el.classList.add("hidden"),1800)}
function esc(value=""){return String(value).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
async function load(selectId){memos=await api("/api/me/memos");renderList();const wanted=selectId||Number(new URLSearchParams(location.search).get("memo"));if(wanted)selectMemo(wanted);else if(current)selectMemo(current.id);else if(memos[0])selectMemo(memos[0].id)}
function renderList(){const q=$("#search").value.trim().toLowerCase();const list=memos.filter(m=>`${m.title} ${m.note} ${m.source_content}`.toLowerCase().includes(q));$("#memo-list").innerHTML=list.length?list.map(m=>`<button data-id="${m.id}" class="${current?.id===m.id?'active':''}"><strong>${esc(m.title)}</strong><span>${esc(m.note||m.source_content||"빈 메모")}</span></button>`).join(""):`<p>저장된 메모가 없습니다.</p>`;$("#memo-list").querySelectorAll("button").forEach(b=>b.onclick=()=>selectMemo(Number(b.dataset.id)))}
function selectMemo(id){current=memos.find(m=>m.id===id);if(!current)return;history.replaceState(null,"",`?memo=${id}`);$("#empty").classList.add("hidden");$("#editor").classList.remove("hidden");$("#memo-title").value=current.title;$("#memo-note").value=current.note;const sourced=Boolean(current.source_message_id);$("#source-card").classList.toggle("hidden",!sourced);$("#source-label").textContent=sourced?`채팅방 ${current.source_room_id||""}`:"직접 작성한 메모";$("#source-sender").textContent=current.source_sender;$("#source-content").textContent=current.source_content;renderTree();renderList()}
function renderTree(){const byParent=new Map();for(const n of current.nodes){const key=n.parent_id??0;if(!byParent.has(key))byParent.set(key,[]);byParent.get(key).push(n)}const branch=(parent=0)=>{const nodes=byParent.get(parent)||[];return nodes.map(n=>`<div class="node-wrap"><article class="node-card"><p>${esc(n.content)}</p><div class="node-actions"><button data-add="${n.id}">＋ 파생</button><button data-edit="${n.id}">수정</button><button data-delete="${n.id}" class="danger">삭제</button></div></article>${(byParent.get(n.id)||[]).length?`<div class="node-children">${branch(n.id)}</div>`:""}</div>`).join("")};const html=branch();$("#memo-tree").innerHTML=html||'<div class="tree-empty">아직 가지가 없습니다. 원문에서 떠오른 첫 생각을 연결해보세요.</div>';$("#memo-tree").querySelectorAll("[data-add]").forEach(b=>b.onclick=()=>openNode("add",Number(b.dataset.add)));$("#memo-tree").querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>openNode("edit",Number(b.dataset.edit)));$("#memo-tree").querySelectorAll("[data-delete]").forEach(b=>b.onclick=()=>removeNode(Number(b.dataset.delete)))}
function openNode(mode,id=null){dialogMode={mode,id};$("#node-dialog-title").textContent=mode==="edit"?"파생 메모 수정":"새 파생 메모";$("#node-content").value=mode==="edit"?current.nodes.find(n=>n.id===id)?.content||"":"";$("#node-dialog").showModal();setTimeout(()=>$("#node-content").focus(),50)}
async function removeNode(id){if(!confirm("이 가지와 아래에 연결된 메모를 모두 삭제할까요?"))return;await api(`/api/me/memo-nodes/${id}`,{method:"DELETE"});await load(current.id);toast("가지를 삭제했습니다")}
$("#node-dialog").addEventListener("close",async()=>{if($("#node-dialog").returnValue!=="default"||!dialogMode)return;const content=$("#node-content").value.trim();if(!content)return toast("내용을 입력하세요");try{if(dialogMode.mode==="edit")await api(`/api/me/memo-nodes/${dialogMode.id}`,{method:"PUT",body:JSON.stringify({content})});else await api(`/api/me/memos/${current.id}/nodes`,{method:"POST",body:JSON.stringify({parent_id:dialogMode.id,content})});await load(current.id);toast("메모를 연결했습니다")}catch(e){alert(e.message)}});
$("#node-save").onclick=()=>$("#node-dialog").close("default");$("#add-root-node").onclick=()=>openNode("add",null);$("#search").oninput=renderList;
$("#new-memo").onclick=async()=>{try{const r=await api("/api/me/memos",{method:"POST",body:JSON.stringify({title:"새 메모",note:""})});await load(r.id);$("#memo-title").focus()}catch(e){alert(e.message)}};
$("#save-root").onclick=async()=>{try{await api(`/api/me/memos/${current.id}`,{method:"PUT",body:JSON.stringify({title:$("#memo-title").value,note:$("#memo-note").value})});await load(current.id);toast("저장했습니다")}catch(e){alert(e.message)}};
$("#delete-root").onclick=async()=>{if(!confirm("이 메모와 모든 가지를 삭제할까요?"))return;await api(`/api/me/memos/${current.id}`,{method:"DELETE"});current=null;history.replaceState(null,"","/memo/");$("#editor").classList.add("hidden");$("#empty").classList.remove("hidden");await load()};
load().catch(e=>{$("#empty").innerHTML=`<b>메모를 불러오지 못했습니다</b><p>${esc(e.message)}</p>`});
